apiVersion: apps/v1
kind: Deployment
metadata:
  name: fn-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fn-backend
  template:
    metadata:
      labels:
        app: fn-backend
    spec:
      containers:
      - name: backend
        image: fastnext-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fn-backend-service
spec:
  type: NodePort
  selector:
    app: fn-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fn-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fn-frontend
  template:
    metadata:
      labels:
        app: fn-frontend
    spec:
      containers:
      - name: frontend
        image: fastnext-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fn-frontend-service
spec:
  type: NodePort
  selector:
    app: fn-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
